name: CI Pipeline
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  go-build-test:
    name: Go Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Download Dependencies
        run: go mod download
      - name: Format Check
        run: test -z "$(gofmt -l .)" || (gofmt -d . && exit 1)
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v -count=1 ./...
